text
Seva144/java-filmorate pull request #1
Opened 2023-01-10 10:03 UTC by Seva144

2023-01-10 15:51 UTC, Seva144 commented
Привет! Надеюсь сейчас получится заново переделал все но почему-то тесты все равно заваливает

2023-01-11 11:02 UTC, ErkinKasymaliev requested changes
Привет, оставил комменты.
Насчет тестов не парьтесь, в этом задании они не нужны. Я до этого имел виду что сборка не проходила

2023-01-11 11:02 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/javafilmorate/model/Film.java
> +    private int id;
почему бы здесь в User не применить валидационные аннотация как в описанию к заданию указано?

2023-01-11 11:02 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/javafilmorate/controllers/FilmController.java
> +    @GetMapping(value = "/films")
можно над классом поставить аннотацию @RequestMapping(value="/films") и он применить этот урл ко всему классу и не прописывать над каждым методом, аналогично и для UserController

2023-01-11 11:02 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/javafilmorate/controllers/FilmController.java
> +        } catch (InvalidNameException | InvalidDescriptionException | InvalidLocalDateException |
все эти исключения давайте удалим и сделаем один - ValidationException.
И давайте проще без try:
public Film createFilm(@RequestBody Film film) {
    validate(film);
    log.debug("Новый фильм добавлен " + film.getName());
    film.setId(generateId());
    films.put(film.getId(), film);
}

аналогично для всех методов во всех контроллерах

2023-01-11 11:02 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/javafilmorate/controllers/FilmController.java
> +    public boolean validateFilm(Film film) throws InvalidNameException, InvalidDescriptionException,
этот метод сделайте void, так как если проверку не пройдет то просто кинет исключение, так что ничего возвращать не надо

2023-01-11 11:02 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/javafilmorate/controllers/FilmController.java
> +        if ((film.getName() == null) || (film.getName().equals(""))) {
если в моделях используйте аннотации для валидации, то этот метод можно существенно сократить или вообще от него избавиться

2023-01-13 20:10 UTC, Seva144 commented
Привет! Были проблемы с push через поддержку решил, добавил валидацию, а теперь тесты не знаю как сделать

2023-01-13 20:11 UTC, Seva144 commented
Привет! Добавил валидацию тесты убрал так как не знаю как их сделать теперь (

2023-01-14 13:43 UTC, ErkinKasymaliev approved these changes
привет, работа принята

2023-01-17 18:23 UTC, merged