TZ10
Seva144/java-filmorate pull request #2
Opened 2023-01-25 20:17 UTC by Seva144

2023-01-26 06:29 UTC, ErkinKasymaliev requested changes
привет, оставил комменты.
давайте использовать логгирование от ломбока вместо LoggerFactory.getLogger(FilmService.class);

2023-01-26 06:29 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/javafilmorate/controllers/FilmController.java
> +@RequestMapping("/films")
хорошо

2023-01-26 06:29 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/javafilmorate/controllers/FilmController.java
>      private final static Logger log = LoggerFactory.getLogger(FilmController.class);
лучше использовать аннотацию от ломбока @Slf4j

2023-01-26 06:29 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/javafilmorate/controllers/FilmController.java
> +    FilmService filmService;
вот тут добавьте модификатор доступа

2023-01-26 06:29 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/javafilmorate/controllers/FilmController.java
> +    @ResponseStatus(HttpStatus.BAD_REQUEST)
уберите этот метод и ниже в отдельный класс, например, ErrorHandler, он будет у вас @RestControllerAdvice

2023-01-26 06:29 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/javafilmorate/controllers/UserController.java
>  public class UserController {
смотрите комменты в FilmController

2023-01-26 06:29 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/javafilmorate/service/FilmService.java
> +        this.filmStorage = FilmorateUtil.getDefaultFilmStorage();
вот этого не надо, у вас уже в InMemoryFilmStorage стоит @Component. Здесь просто 
public FilmService (FilmStorage filmStorage) {
     this.filmStorage = filmStorage;
}
FilmorateUtil уже не нужен, удалите его

2023-01-26 06:29 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/javafilmorate/service/UserService.java
> +        this.userStorage= FilmorateUtil.getDefaultUserStorage();
смотрите комменты в FilmService

2023-01-26 06:29 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/javafilmorate/storage/InMemoryFilmStorage.java
> +    private final static HashMap<Integer, Film> films = new HashMap<>();
статиком не надо делать

2023-01-26 17:54 UTC, Seva144 commented on src/main/java/ru/yandex/practicum/javafilmorate/service/FilmService.java
> +
Добрый день Эркин! По поводу утилитарного класса, я его использовал чтобы validateId метод сделать для проверки добавляемого id user в класс фильм, я тогда не знаю как достать id пользователя в классе FilmService

2023-01-26 17:55 UTC, Seva144 commented on src/main/java/ru/yandex/practicum/javafilmorate/service/FilmService.java
> +        this.filmStorage = FilmorateUtil.getDefaultFilmStorage();
Добрый день Эркин! По поводу утилитарного класса, я его использовал чтобы validateId метод сделать для проверки добавляемого id user в класс фильм, я тогда не знаю как достать id пользователя в классе FilmService

2023-01-27 06:02 UTC, ErkinKasymaliev requested changes
оставил комменты

2023-01-27 06:02 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/javafilmorate/controllers/ErrorHandler.java
> +@RestControllerAdvice
хорошо

2023-01-27 06:02 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/javafilmorate/service/FilmService.java
> +        this.filmStorage = FilmorateUtil.getDefaultFilmStorage();
Добрый день!
Сделайте как выше написал, а насчет метода validateId просто заинжектите сюда также UserStorage и используйте метод getUser(userId) для проверки существования юзера

2023-01-28 07:12 UTC, ErkinKasymaliev approved these changes
Работа принята

2023-02-07 16:50 UTC, merged