TZ11
Seva144/java-filmorate pull request #3
Opened 2023-02-21 23:08 UTC by Seva144

2023-02-22 11:09 UTC, Seva144 commented
Добрый день Еркин! Сделал ТЗ 11 но пока без тестов, пока их буду делать чтобы было понимание что еще исправить, а то мне до пятницы необходимо сдать
Спасибо большое!

2023-02-22 13:51 UTC, Seva144 commented
Можно использовать обычные junit тесты?

2023-02-23 12:16 UTC, ErkinKasymaliev requested changes
привет, оставил комменты

2023-02-23 12:16 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/javafilmorate/service/FilmService.java
> +        films.forEach(film -> film.setMpa(filmStorage.getMpa(film.getMpa().getId())));
так и ниже не пойдет, вы сперва получили список всех фильмов, а потом для каждого из них делаете 2 запроса. Представьте что в базе у вас 100000 фильмов и каждый сделает еще 2 запроса.
filmStorage.getAllFilms - перепишите с join-ми что бы сразу светились жанры и рейтинг

2023-02-23 12:16 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/javafilmorate/service/FilmService.java
> +        if (filmStorage.getFilm(idFilm) != null) {
смотрите коммент выше

2023-02-23 12:16 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/javafilmorate/service/FilmService.java
> +        List<Film> films = filmStorage.getTopFilms(count).stream().limit(count)
комменты выше

2023-02-23 12:16 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/javafilmorate/service/UserService.java
> +        if (userStorage.getUser(id) != null) {
можно заюзать Optional, или 
return userStorage.getUser(id) != null  ? userStorage.getUser(id) : throw new NotFoundException();

2023-02-23 12:16 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/javafilmorate/dao/FilmMapper.java
> +public class FilmMapper implements RowMapper<Film> {
странно что мапперы у вас в пакете Dao, лучше перенесите их в пакет mapper. А вот то что у вас в пакете storarage должно быть в Dao

2023-02-24 01:02 UTC, Seva144 commented
Доброй ночи Эркин! исправил по замечаниям

2023-02-24 05:28 UTC, ErkinKasymaliev approved these changes
привет, работа принята!
Со следующей работы жду тесты

2023-02-27 19:36 UTC, merged